import { useEffect, useMemo, useState } from 'react';
import './JevRoutingStudy.css';

type Subset = 'overall' | 'positive' | 'multi' | 'one_tool' | 'negative';
type Metric = { n: number; exactCorrect: number; exactAccuracy: number; selectionCorrect: number; selectionAccuracy: number };
type Latency = { mean: number; p50: number; p95: number; max: number; first: number; n: number };
type Model = {
  id: string; name: string; accuracy: Record<Subset, number>; correct: Record<Subset, number>;
  metrics: Record<string, Metric>; latencyMs: Latency; latencyBySubset?: Record<string, Latency>;
  checkpoint: { repo?: string; revision?: string }; runtime: { precision?: string; interface?: string };
};
type Prediction = { selectedAction: string; selectedTools: string[]; correct: boolean; exactCorrect: boolean; latencyMs: number; probabilities: Record<string, number> };
type Case = {
  id: string; stratum: string; category: string; prompt: string; stateText?: string;
  options: { id: string; description: string; kind: string }[];
  expectedTools: string[]; goldAction: string; predictions: Record<string, Prediction>;
};
export type Report = { schema: string; models: Model[]; cases: Case[]; dataset: { source_commit?: string; cases_sha256?: string }; };

const DATA_URL = '/jev-style-evals/bfcl-v1/report.json';
const HF_URL = 'https://huggingface.co/datasets/pyuvraj/bfcl-v1-jev-routing';
const subsets: { id: Subset; label: string; count: number; note: string }[] = [
  { id: 'overall', label: 'All cases', count: 250, note: 'Exact function on tool-required cases; any non-tool action on no-call cases.' },
  { id: 'positive', label: 'Tool required', count: 200, note: 'Select the exact reference function. This is the 200-case tool-selection view.' },
  { id: 'multi', label: 'Multiple tools', count: 150, note: 'Choose the reference function from several available functions.' },
  { id: 'one_tool', label: 'One tool', count: 50, note: 'Decide to use the single available function instead of a non-tool action.' },
  { id: 'negative', label: 'No call', count: 50, note: 'No function fits. no_tool, clarify and cannot_answer all count as non-tool selections.' },
];
const shortName = (model: Model) => /semif|qwen/i.test(model.name) ? 'Qwen · SemIf' : /nimble/i.test(model.name) ? 'Nimble' : /nanojev/i.test(model.name) ? 'NanoJev' : /rizzo/i.test(model.name) ? 'Rizzo' : /laya/i.test(model.name) ? 'Laya' : /kev/i.test(model.name) ? 'Kev' : /von/i.test(model.name) ? 'Von' : model.name;
const color = (model: Model) => ({ Laya: '#087f75', Kev: '#7b668f', Nimble: '#ad5d36', 'Qwen · SemIf': '#293e51', Rizzo: '#b99033', Von: '#6c8c84', NanoJev: '#96958d' }[shortName(model)] || '#546774');
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
const ms = (value?: number) => value === undefined || !Number.isFinite(value) ? '—' : `${value.toFixed(1)} ms`;
const sections = [['why', 'The question'], ['setup', 'What I measured'], ['results', 'The results'], ['speed', 'The speed question'], ['explore', 'Inspect a case'], ['limits', 'What this leaves open'], ['next', 'What comes next'], ['references', 'Sources & credits']];

function AccuracyChart({ report }: { report: Report }) {
  const [subset, setSubset] = useState<Subset>('overall');
  const [sort, setSort] = useState('accuracy');
  const selected = subsets.find(item => item.id === subset)!;
  const models = [...report.models].sort((a, b) => sort === 'accuracy' ? b.accuracy[subset] - a.accuracy[subset] : shortName(a).localeCompare(shortName(b)));
  return <div className="jev-figure" aria-labelledby="accuracy-title">
    <div className="jev-figure-heading"><div><span className="jev-figure-number">Figure 01</span><h3 id="accuracy-title">The denominator matters.</h3><p>Seven systems. The same cases. Five views.</p></div><label className="jev-sort">Order<select value={sort} onChange={e => setSort(e.target.value)}><option value="accuracy">Accuracy</option><option value="name">Name</option></select></label></div>
    <div className="jev-tabs" role="group" aria-label="Accuracy subset">{subsets.map(item => <button key={item.id} type="button" aria-pressed={subset === item.id} onClick={() => setSubset(item.id)}>{item.label}<span>{item.count}</span></button>)}</div>
    <div className="jev-bar-chart" role="img" aria-label={`Selection accuracy on ${selected.count} ${selected.label.toLowerCase()} cases. ${models.map(m => `${shortName(m)} ${pct(m.accuracy[subset])}`).join('; ')}.`}>
      <div className="jev-bar-axis"><span>0</span><span>25</span><span>50</span><span>75</span><span>100%</span></div>
      {models.map(model => <div className="jev-bar-row" key={model.id}><div className="jev-bar-name"><i style={{ background: color(model) }} />{shortName(model)}</div><div className="jev-bar-track"><div className="jev-bar-fill" style={{ width: pct(model.accuracy[subset]), background: color(model) }} /></div><div className="jev-bar-value"><strong>{pct(model.accuracy[subset])}</strong><span>{model.correct[subset]} / {selected.count}</span></div></div>)}
    </div>
    <p className="jev-caption"><strong>{selected.label}, n = {selected.count}.</strong> {selected.note} These are routing decisions, not generated function calls or completed tasks.</p>
  </div>;
}

function SpeedChart({ report }: { report: Report }) {
  const [subset, setSubset] = useState<'overall' | 'positive'>('overall');
  const [stat, setStat] = useState<'p50' | 'mean'>('p50');
  const [selectedId, setSelectedId] = useState(report.models.find(m => /laya/i.test(m.name))?.id || report.models[0].id);
  const latency = (model: Model) => model.latencyBySubset?.[subset === 'overall' ? 'all' : 'positive'] || model.latencyMs;
  const xMax = Math.ceil(Math.max(...report.models.map(m => latency(m)[stat])) / 20) * 20 + 20;
  const x = (value: number) => 68 + value / xMax * 700;
  const y = (value: number) => 328 - value * 244;
  const selected = report.models.find(m => m.id === selectedId) || report.models[0];
  const offsets: Record<string, [number, number]> = { Laya: [12, -6], Von: [12, 20], NanoJev: [12, -10], Kev: [10, 18], Rizzo: [12, 30], Nimble: [6, -31], 'Qwen · SemIf': [-8, -10] };
  return <div className="jev-figure jev-speed-figure" aria-labelledby="speed-title">
    <div className="jev-figure-heading"><div><span className="jev-figure-number">Figure 02 · exploratory timing</span><h3 id="speed-title">Fast decisions, under these conditions.</h3><p>H100 measurements. Mixed runtimes. One recorded call per case.</p></div></div>
    <div className="jev-chart-controls"><label>Cases<select value={subset} onChange={e => setSubset(e.target.value as 'overall' | 'positive')}><option value="overall">All 250 cases</option><option value="positive">200 tool-required cases</option></select></label><label>Latency<select value={stat} onChange={e => setStat(e.target.value as 'p50' | 'mean')}><option value="p50">Median</option><option value="mean">Mean · includes first-call overhead</option></select></label></div>
    <div className="jev-scatter-wrap"><svg viewBox="0 0 830 390" className="jev-scatter" role="img" aria-labelledby="scatter-title scatter-desc"><title id="scatter-title">{`Routing accuracy against recorded ${stat === 'p50' ? 'median' : 'mean'} wall latency`}</title><desc id="scatter-desc">Higher and farther left is better on this selected subset. All measurements are exploratory H100 results. Choose a model below for exact values.</desc>
      {[0, .25, .5, .75, 1].map(tick => <g key={tick}><line x1="68" x2="786" y1={y(tick)} y2={y(tick)} stroke="#e6e9e4" /><text x="52" y={y(tick) + 4} textAnchor="end">{tick * 100}%</text></g>)}
      {[0, 1, 2, 3, 4].map(i => <g key={i}><line x1={x(xMax * i / 4)} x2={x(xMax * i / 4)} y1="72" y2="328" stroke="#f0f0eb" /><text x={x(xMax * i / 4)} y="351" textAnchor="middle">{(xMax * i / 4).toFixed(0)}</text></g>)}
      <text x="68" y="34" className="jev-axis-title">SELECTION ACCURACY ↑</text><text x="418" y="381" textAnchor="middle" className="jev-axis-title">RECORDED WALL LATENCY (MS) →</text>
      {report.models.map(model => { const offset = offsets[shortName(model)] || [10, -10]; return <g key={model.id} className={selectedId === model.id ? 'jev-point is-selected' : 'jev-point'}><title>{`${model.name}: ${pct(model.accuracy[subset])}, ${ms(latency(model)[stat])}`}</title><circle cx={x(latency(model)[stat])} cy={y(model.accuracy[subset])} r={selectedId === model.id ? 10 : 7} fill={color(model)} stroke="#fff" strokeWidth="3" /><text x={x(latency(model)[stat]) + offset[0]} y={y(model.accuracy[subset]) + offset[1]} textAnchor={shortName(model) === 'Qwen · SemIf' ? 'end' : 'start'}>{shortName(model)}</text></g>; })}
    </svg></div>
    <div className="jev-model-picker" role="group" aria-label="Inspect model timing">{report.models.map(model => <button type="button" key={model.id} aria-pressed={selectedId === model.id} onClick={() => setSelectedId(model.id)}><i style={{ background: color(model) }} />{shortName(model)}</button>)}</div>
    <div className="jev-model-detail" aria-live="polite"><strong>{selected.name}</strong><span><b>{pct(selected.accuracy[subset])}</b> selection accuracy</span><span><b>{ms(latency(selected)[stat])}</b> {stat === 'p50' ? 'median' : 'mean'} wall time</span><span>{selected.runtime?.precision || 'See run metadata'}</span></div>
    <p className="jev-caption">No evaluator warm-up or repeated-run timing protocol. HTTP and in-process adapters, precisions and serving paths differ. First recorded calls remain in the aggregates. These values do not establish Mac latency or an architecture-only speed advantage.</p>
  </div>;
}

function CaseExplorer({ report }: { report: Report }) {
  const [query, setQuery] = useState('');
  const [failuresOnly, setFailuresOnly] = useState(false);
  const [modelId, setModelId] = useState(report.models.find(m => /laya/i.test(m.name))?.id || report.models[0].id);
  const [caseId, setCaseId] = useState(report.cases.find(c => c.predictions[modelId]?.correct === false)?.id || report.cases[0].id);
  const filtered = useMemo(() => report.cases.filter(c => `${c.id} ${c.prompt} ${c.goldAction}`.toLowerCase().includes(query.toLowerCase()) && (!failuresOnly || c.predictions[modelId]?.correct === false)), [report, query, failuresOnly, modelId]);
  const active = filtered.find(c => c.id === caseId) || filtered[0];
  const prediction = active?.predictions[modelId];
  const model = report.models.find(m => m.id === modelId)!;
  return <div className="jev-explorer">
    <div className="jev-explorer-top"><span className="jev-figure-number">Open the evidence</span><span className="jev-live-dot">250 public cases · 1,750 predictions</span></div>
    <div className="jev-explorer-controls"><label>Find a case<input type="search" placeholder="Request, function, or case ID…" value={query} onChange={e => setQuery(e.target.value)} /></label><label>Model<select value={modelId} onChange={e => setModelId(e.target.value)}>{report.models.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div>
    <div className="jev-case-filter"><label><input type="checkbox" checked={failuresOnly} onChange={e => setFailuresOnly(e.target.checked)} /> Only this model’s mistakes</label><span aria-live="polite">{filtered.length} matching {filtered.length === 1 ? 'case' : 'cases'}</span></div>
    {active && prediction ? <>
      <label className="jev-case-select">Case<select value={active.id} onChange={e => setCaseId(e.target.value)}>{filtered.map(c => <option key={c.id} value={c.id}>{c.id} · {c.prompt.slice(0, 80)}</option>)}</select></label>
      <div className="jev-case-body"><div className="jev-case-request"><div className="jev-case-eyebrow">USER REQUEST <span>{active.expectedTools.length ? `${active.options.filter(o => o.kind === 'tool').length || active.options.length - 3} function options` : 'No call expected'}</span></div><p>{active.prompt}</p><div className="jev-case-target"><span>Reference</span><strong>{active.expectedTools.length ? active.expectedTools.join(', ') : 'Any non-tool action'}</strong></div><details><summary>Read all options shown to the model</summary><dl>{active.options.map(option => <div key={option.id}><dt>{option.id}</dt><dd>{option.description}</dd></div>)}</dl></details></div>
      <div className="jev-case-prediction"><div className="jev-case-eyebrow">{shortName(model).toUpperCase()}’S DECISION <span className={prediction.correct ? 'jev-status-good' : 'jev-status-bad'}>{prediction.correct ? 'Correct' : 'Incorrect'}</span></div><h4>{prediction.selectedAction}</h4><p className="jev-case-latency">Recorded wall time · {ms(prediction.latencyMs)}</p><div className="jev-probabilities">{Object.entries(prediction.probabilities || {}).sort((a, b) => b[1] - a[1]).map(([option, probability]) => <div key={option} className="jev-prob-row"><div><span>{option}</span><b>{(probability * 100).toFixed(1)}%</b></div><div className="jev-prob-track"><span style={{ width: pct(probability), background: option === prediction.selectedAction ? color(model) : '#c8d0ca' }} /></div></div>)}</div><p className="jev-microcopy">Saved option probabilities. They are not a calibrated guarantee of correctness.</p></div></div>
      <div className="jev-case-comparison"><span>On this same case</span>{report.models.map(m => <button type="button" key={m.id} onClick={() => { setCaseId(active.id); if (failuresOnly && active.predictions[m.id]?.correct) setFailuresOnly(false); setModelId(m.id); }} aria-pressed={m.id === modelId}><span aria-label={active.predictions[m.id]?.correct ? 'Correct' : 'Incorrect'}>{active.predictions[m.id]?.correct ? '✓' : '×'}</span>{shortName(m)}</button>)}</div>
    </> : <p className="jev-empty">No cases match. Try another search or turn off the mistakes filter.</p>}
  </div>;
}

function ResultsTable({ report }: { report: Report }) {
  return <div className="jev-table-scroll" tabIndex={0} role="region" aria-label="Complete model results, scroll horizontally on small screens"><table className="jev-results-table"><caption>Complete results · all 250 cases</caption><thead><tr><th scope="col">System</th><th scope="col">Selection</th><th scope="col">Tool required</th><th scope="col">No call</th><th scope="col">Median</th><th scope="col">Precision</th></tr></thead><tbody>{report.models.map(m => <tr key={m.id}><th scope="row"><i style={{ background: color(m) }} />{m.name}</th><td><strong>{pct(m.accuracy.overall)}</strong><small>{m.correct.overall}/250</small></td><td>{m.correct.positive}/200</td><td>{m.correct.negative}/50</td><td>{ms(m.latencyMs.p50)}</td><td>{m.runtime?.precision || 'See metadata'}</td></tr>)}</tbody></table></div>;
}

export default function JevRoutingStudy({ initialReport }: { initialReport?: Report } = {}) {
  const [report, setReport] = useState<Report | null>(initialReport || null);
  const [error, setError] = useState(false);
  const [activeSection, setActiveSection] = useState('why');
  useEffect(() => {
    if (initialReport) return;
    const controller = new AbortController();
    fetch(DATA_URL, { signal: controller.signal }).then(response => { if (!response.ok) throw new Error('Report unavailable'); return response.json(); }).then(setReport).catch(e => { if (e.name !== 'AbortError') setError(true); });
    return () => controller.abort();
  }, [initialReport]);
  useEffect(() => {
    const originalTitle = document.title;
    document.title = 'Can small decision models choose the right tool? | Pritish Yuvraj';
    const observer = new IntersectionObserver(entries => { const entry = entries.find(item => item.isIntersecting); if (entry) setActiveSection(entry.target.id); }, { rootMargin: '-12% 0px -68% 0px' });
    sections.forEach(([id]) => { const element = document.getElementById(id); if (element) observer.observe(element); });
    return () => { observer.disconnect(); document.title = originalTitle; };
  }, []);
  return <div className="jev-study">
    <a className="jev-skip-link" href="#study-content">Skip to article</a>
    <header className="jev-header"><a href="/" className="jev-wordmark">Pritish Yuvraj<span>Research notes</span></a><nav aria-label="Article navigation"><a href="#results">Results</a><a href="#explore">Explore cases</a><a href={HF_URL} target="_blank" rel="noreferrer">Data & code <span aria-hidden="true">↗</span></a></nav></header>
    <main id="study-content">
      <div className="jev-hero"><div className="jev-kicker"><span>Jev-style evaluations</span><i />Study 01 · September 28, 2026</div><h1>Can a small model<br />choose the <em>right tool?</em></h1><p className="jev-deck">I want a useful assistant that runs on my Mac. Before trusting a small model to steer it, I compared seven decision systems on 250 BFCL-derived routing cases.</p><div className="jev-byline"><span className="jev-avatar">PY</span><div><strong>Pritish Yuvraj</strong><span>Personal research · a first measurement</span></div><a href="#results">Jump to the results <span aria-hidden="true">↓</span></a></div>
      <div className="jev-hero-metrics"><div><strong>7</strong><span>decision systems</span></div><div><strong>250</strong><span>shared evaluation cases</span></div><div><strong>1</strong><span>routing step per case</span></div><p><span className="jev-small-label">Scope of this study</span>Function selection.<br />Arguments and execution come later.</p></div></div>
      <div className="jev-article-layout"><aside className="jev-toc"><span className="jev-small-label">On this page</span><nav aria-label="Table of contents">{sections.map(([id, label], index) => <a href={`#${id}`} key={id} aria-current={activeSection === id ? 'location' : undefined}><span>{String(index + 1).padStart(2, '0')}</span>{label}</a>)}</nav><a className="jev-toc-download" href={DATA_URL} download>Download the report <span aria-hidden="true">↓</span></a></aside><article className="jev-article">
      <section id="why" className="jev-section"><div className="jev-section-label">01 / The question</div><h2>A local assistant needs a good next move.</h2><div className="jev-prose"><p>The motivation is personal. I’m building an assistant for the things I do on my own computer: finding information, working with files, searching the web, and managing everyday tasks. I want its models to run locally.</p><p>A tool catalog adds a lot of work to a small chat model. Before it can help, it has to read the available tools, choose one, produce arguments, interpret the result, and decide whether to continue. My question was whether we can give the <strong>selection decision</strong> to a smaller, faster model.</p><p>The intended division of work is simple: a decision model chooses the next action; Qwen fills the selected tool’s arguments and explains the result; the harness executes tools and enforces permissions. After a result arrives, the decision model chooses again. A low-confidence decision can fall back to Qwen.</p></div>
      <div className="jev-flow" aria-label="Proposed local assistant architecture"><div className="jev-flow-step"><span>01 · Read</span><h3>Request + state</h3><p>History, latest result,<br />available tools</p></div><span className="jev-flow-arrow" aria-hidden="true">→</span><div className="jev-flow-step jev-flow-decision"><span>02 · Decide</span><h3>Small selector</h3><p>Choose a tool,<br />or choose to stop</p><b>This study</b></div><span className="jev-flow-arrow" aria-hidden="true">→</span><div className="jev-flow-step"><span>03 · Act</span><h3>Qwen + harness</h3><p>Arguments, permissions,<br />execution, response</p></div></div>
      <div className="jev-prose"><p>Jev-style systems return a choice or a distribution over supplied options without generating a free-form answer. That interface is useful here. It is also an existing idea: this is an evaluation of available systems, with a practical assistant as the motivation.</p><p>The first experiment asks a narrower question: <strong>given a user request and a few tool descriptions, which action does each system select?</strong></p></div></section>

      <section id="setup" className="jev-section"><div className="jev-section-label">02 / What I measured</div><h2>A small, inspectable routing test.</h2><div className="jev-prose"><p>I converted a selected subset of <a href="https://gorilla.cs.berkeley.edu/blogs/8_berkeley_function_calling_leaderboard.html" target="_blank" rel="noreferrer">Berkeley Function Calling Leaderboard V1</a> into decision requests. Each system receives the same user request, shortened tool descriptions, and three non-tool choices: <code>no_tool</code>, <code>clarify</code>, and <code>cannot_answer</code>.</p><p>The cases contain <strong>one to four function options</strong>. Tool descriptions are capped at 120 characters; full argument schemas are not supplied. For Laya, the rendered requests span just <strong>104–271 tokens</strong>. This is a short-input study.</p></div>
      <div className="jev-composition"><span className="jev-figure-number">The 250-case subset</span><div className="jev-composition-track" role="img" aria-label="150 multiple-tool cases, 50 one-tool cases, and 50 no-call cases"><div style={{ width: '60%' }}>150</div><div style={{ width: '20%' }}>50</div><div style={{ width: '20%' }}>50</div></div><div className="jev-composition-labels"><div><i /><strong>Multiple tools</strong><span>150 cases · a function is required</span></div><div><i /><strong>One tool</strong><span>50 cases · the function is required</span></div><div><i /><strong>No call</strong><span>50 cases · no function fits</span></div></div></div>
      <div className="jev-definition-grid"><div><span className="jev-small-label">When a tool is required</span><h3>Exact function selection</h3><p>The selected function must match the reference function. Producing valid arguments is outside this test.</p></div><div><span className="jev-small-label">When no tool fits</span><h3>Any non-tool action</h3><p>The source labels do not distinguish stopping, clarification, and inability. All three count as a correct non-tool selection.</p></div></div>
      <p className="jev-note"><strong>A derived evaluation, with its own metric.</strong> The results below are not official BFCL scores. They do not measure argument generation, tool execution, permission handling, or complete assistant tasks.</p></section>

      <section id="results" className="jev-section"><div className="jev-section-label">03 / The results</div><h2>Strong selection on short inputs.<br /><span>A much narrower claim than a good agent.</span></h2><div className="jev-prose"><p>All seven systems completed the same 250 cases. On the 200 requests that require a function, Nimble chose the reference function in every case; Qwen with SemIf missed two, and Laya missed three. Including the 50 no-call cases changes the picture.</p><p>The interactive chart keeps those denominators visible. The full set uses the combined selection metric; the tool-required views use exact function selection.</p></div>
      {report ? <><AccuracyChart report={report} /><ResultsTable report={report} /></> : <div className="jev-loading" role="status">{error ? <>The interactive report could not load. <a href={HF_URL}>Read the published data on Hugging Face.</a></> : 'Loading the recorded results…'}</div>}
      <div className="jev-findings"><div><span>01</span><h3>Laya is a credible candidate.</h3><p>Its 197/200 tool-required result makes it worth testing in the assistant. Its lower full-set score also makes abstention worth investigating.</p></div><div><span>02</span><h3>The frozen baseline is strong.</h3><p>SemIf reads option logits directly from Qwen3.5-4B. Its result shows why this baseline belongs beside specialized decision checkpoints.</p></div><div><span>03</span><h3>Specialization cuts both ways.</h3><p>NanoJev’s released checkpoint targets games. In this run it frequently chose non-tool actions. That result does not diagnose its architecture.</p></div></div>
      <div className="jev-prose"><p>With only 200 positive cases, one or two mistakes separate the top systems. I would not use that gap to declare a general winner. The useful signal is that several systems can do this particular selection task well enough to justify a harder test.</p></div></section>

      <section id="speed" className="jev-section"><div className="jev-section-label">04 / The speed question</div><h2>What did the fast part actually cost?</h2><div className="jev-prose"><p>The runs were recorded on an <strong>NVIDIA H100</strong>. They use different runtimes, precisions and request paths. These timings are an exploratory view of the tested systems; there is no Mac performance result in this study.</p><p>Both axes below refer to the same selected subset. Switch between median and mean to see why the timing summary matters: first-call overhead remains in the logs, and no evaluator warm-up was performed.</p></div>
      {report && <SpeedChart report={report} />}
      <div className="jev-prose"><p>A fast selector can help only when it removes enough work elsewhere. The relevant budget includes selector time, Qwen’s argument generation, tool execution, retries, fallback and the final response. Adding a router can increase total time when it repeatedly falls back.</p><p>The chat model may also need much of the same evidence to produce correct arguments or explain a result. Moving tool selection into another model does not automatically remove that context from Qwen.</p></div>
      <div className="jev-equation"><span className="jev-small-label">The measurement I ultimately care about</span><p>Request <span>→</span> routing <span>→</span> arguments <span>→</span> tools <span>→</span> useful result</p><strong>Successful task completion, and time to get there.</strong></div></section>

      <section id="explore" className="jev-section"><div className="jev-section-label">05 / Inspect a case</div><h2>Read the decisions behind the averages.</h2><div className="jev-prose"><p>Search the public requests, inspect the offered options, and compare all seven systems on the same case. The mistakes filter applies to the selected model.</p></div>{report && <CaseExplorer report={report} />}<p className="jev-caption">Only benchmark requests and recorded model predictions appear here. These are not private assistant conversations.</p></section>

      <section id="limits" className="jev-section"><div className="jev-section-label">06 / What this leaves open</div><h2>The next experiment needs to be harder.</h2><div className="jev-limit-list"><div><span>01</span><div><h3>Long context and a real tool catalog</h3><p>One to four short function descriptions do not resemble dozens of assistant tools plus conversation history. The Laya inputs here stay below 272 tokens. No long-context conclusion follows from these results.</p></div></div><div><span>02</span><div><h3>The decision after a tool result</h3><p>First-step selection does not test whether the model notices completion, recovers from an error, asks for missing information, or avoids repeating a successful command.</p></div></div><div><span>03</span><div><h3>Calibration and fallback</h3><p>A high option probability is not proof of correctness. A fallback threshold must be chosen on separate development data and tested on untouched cases, with both error rate and coverage reported.</p></div></div><div><span>04</span><div><h3>Clean comparison and dataset overlap</h3><p>These systems differ in checkpoint, training data, precision and serving code. Public benchmark exposure in their base models is not ruled out. A selected BFCL-derived subset cannot establish broad generalization.</p></div></div><div><span>05</span><div><h3>Safety and task success</h3><p>A correct tool name does not imply safe or correct arguments. Permission checks belong in the harness. A personal assistant still needs verification at the level of outcomes.</p></div></div></div></section>

      <section id="next" className="jev-section"><div className="jev-section-label">07 / What comes next</div><h2>From a routing score<br />to a useful local assistant.</h2><div className="jev-next-grid"><div><span>01 / Broaden the cases</span><h3>Less saturation. More ambiguity.</h3><p>Add BFCL V2 community cases and When2Call decisions about whether to call, clarify or decline. Keep their shared provenance visible.</p></div><div><span>02 / Test the loop</span><h3>Learn from real decision states.</h3><p>Build an opt-in, reviewed collection of personal-assistant traces, including tool results, failures and stopping decisions. Keep an untouched scenario-level test set.</p></div><div><span>03 / Measure on the Mac</span><h3>Compare complete tasks.</h3><p>Hold the chat model, tools, permissions and tasks fixed. Compare Qwen-only routing with the selector, including memory use, fallback, success and wall time.</p></div></div><div className="jev-prose"><p>My working conclusion is modest: <strong>small decision models deserve a place in the experiment.</strong> This pilot gives me a reason to continue. Whether they make the assistant more useful—and meaningfully faster—still needs to be measured.</p></div><div className="jev-artifact-cta"><div><span className="jev-small-label">Make this result inspectable</span><h3>Cases, predictions and conversion code.</h3><p>The public release includes the evaluation inputs and per-case outputs so the aggregate scores can be checked.</p></div><a href={HF_URL} target="_blank" rel="noreferrer">Explore on Hugging Face <span aria-hidden="true">↗</span></a></div></section>

      <section id="references" className="jev-section jev-references"><div className="jev-section-label">08 / Sources & credits</div><h2>A shared idea, an open comparison.</h2><p>This study builds on existing work in typed decisions and function-calling evaluation. Jev is TypeSafe’s product; the systems tested here are independently developed open alternatives and readout methods.</p><ol><li><a href="https://gorilla.cs.berkeley.edu/blogs/8_berkeley_function_calling_leaderboard.html" target="_blank" rel="noreferrer">Berkeley Function Calling Leaderboard</a><span>Source benchmark and original function-calling evaluation.</span></li><li><a href="https://blobfish.ai/benchmarks/typed-decision-bench/tasks/bfcl-tool-dispatch" target="_blank" rel="noreferrer">Blobfish · BFCL tool dispatch</a><span>Related evaluation of tool dispatch as a typed decision.</span></li><li><a href="https://huggingface.co/mvbalaji/od1-base" target="_blank" rel="noreferrer">OD1</a><span>Related open decision-model work.</span></li><li><a href="https://github.com/TheoLeeCJ/SemIf-OpenJev" target="_blank" rel="noreferrer">SemIf</a><span>Direct option-logit scoring, including the frozen Qwen baseline used here.</span></li><li><a href="https://langwatch.ai/compare/jev-vs-all" target="_blank" rel="noreferrer">LangWatch · Jev comparisons</a><span>Related comparisons across decision systems.</span></li><li><a href="https://github.com/NVIDIA/When2Call" target="_blank" rel="noreferrer">When2Call</a><span>Call, clarify and unavailable-tool decisions; training and test provenance are documented separately.</span></li></ol><div className="jev-model-credits"><span className="jev-small-label">The systems</span><p><a href="https://huggingface.co/convaiinnovations/laya-typed-decisions" target="_blank" rel="noreferrer">Laya</a> · <a href="https://github.com/jaredpalmer/kev" target="_blank" rel="noreferrer">Kev</a> · <a href="https://github.com/bespokelabsai/nimble" target="_blank" rel="noreferrer">Nimble</a> · <a href="https://github.com/TheoLeeCJ/SemIf-OpenJev" target="_blank" rel="noreferrer">Qwen + SemIf</a> · <a href="https://github.com/Rizzo-AI-Academy/rizzo-flow" target="_blank" rel="noreferrer">Rizzo Flow</a> · <a href="https://github.com/wfzyx/von" target="_blank" rel="noreferrer">Von</a> · <a href="https://github.com/TianyuCodings/NanoJev" target="_blank" rel="noreferrer">NanoJev</a></p></div></section>
      </article></div>
    </main><footer className="jev-footer"><a href="/">← Back to Pritish Yuvraj</a><span>Jev-style evaluations / Study 01</span><a href="#study-content">Back to top ↑</a></footer>
  </div>;
}
