import { useEffect, useMemo, useState } from 'react';
import './JevRoutingStudy.css';

type Subset = 'overall' | 'positive' | 'multi' | 'one_tool' | 'negative';
type Metric = { n: number; exactCorrect: number; exactAccuracy: number; selectionCorrect: number; selectionAccuracy: number };
type Latency = { mean: number; p50: number; p95: number; max: number; first: number; n: number };
type Model = {
  id: string; name: string; accuracy: Record<Subset, number>; correct: Record<Subset, number>;
  metrics: Record<string, Metric>; latencyMs: Latency; latencyBySubset?: Record<string, Latency>;
  checkpoint: { repo?: string; revision?: string }; runtime: { precision?: string; interface?: string };
};
type Prediction = { selectedAction: string; selectedTools: string[]; correct: boolean; exactCorrect: boolean; latencyMs: number; probabilities: Record<string, number> };
type Case = {
  id: string; stratum: string; category: string; prompt: string; stateText?: string;
  options: { id: string; description: string; kind: string }[];
  expectedTools: string[]; goldAction: string; predictions: Record<string, Prediction>;
};
export type Report = { schema: string; models: Model[]; cases: Case[]; dataset: { source_commit?: string; cases_sha256?: string }; };

const DATA_URL = '/jev-style-evals/bfcl-v1/report.json';
const HF_URL = 'https://huggingface.co/datasets/pyuvraj/bfcl-v1-jev-routing';
const subsets: { id: Subset; label: string; count: number; note: string }[] = [
  { id: 'overall', label: 'All cases', count: 250, note: 'Exact function on tool-required cases; any non-tool action on no-call cases.' },
  { id: 'positive', label: 'Tool required', count: 200, note: 'Select the exact reference function. This is the 200-case tool-selection view.' },
  { id: 'multi', label: 'Multiple tools', count: 150, note: 'Choose the reference function from several available functions.' },
  { id: 'one_tool', label: 'One tool', count: 50, note: 'Decide to use the single available function instead of a non-tool action.' },
  { id: 'negative', label: 'No call', count: 50, note: 'No function fits. no_tool, clarify and cannot_answer all count as non-tool selections.' },
];
const shortName = (model: Model) => /semif|qwen/i.test(model.name) ? 'Qwen · SemIf' : /nimble/i.test(model.name) ? 'Nimble' : /nanojev/i.test(model.name) ? 'NanoJev' : /rizzo/i.test(model.name) ? 'Rizzo' : /laya/i.test(model.name) ? 'Laya' : /kev/i.test(model.name) ? 'Kev' : /von/i.test(model.name) ? 'Von' : model.name;
const color = (model: Model) => ({ Laya: '#087f75', Kev: '#7b668f', Nimble: '#ad5d36', 'Qwen · SemIf': '#293e51', Rizzo: '#b99033', Von: '#6c8c84', NanoJev: '#96958d' }[shortName(model)] || '#546774');
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
const ms = (value?: number) => value === undefined || !Number.isFinite(value) ? '—' : `${value.toFixed(1)} ms`;
const sections = [['abstract', 'Abstract'], ['why', 'Introduction'], ['setup', 'Experimental setup'], ['results', 'Selection accuracy'], ['speed', 'Latency analysis'], ['explore', 'Prediction analysis'], ['limits', 'Limitations'], ['next', 'Conclusion'], ['references', 'References']];

function AccuracyChart({ report }: { report: Report }) {
  const [subset, setSubset] = useState<Subset>('overall');
  const [sort, setSort] = useState('accuracy');
  const selected = subsets.find(item => item.id === subset)!;
  const models = [...report.models].sort((a, b) => sort === 'accuracy' ? b.accuracy[subset] - a.accuracy[subset] : shortName(a).localeCompare(shortName(b)));
  return <div className="jev-figure" aria-labelledby="accuracy-title">
    <div className="jev-figure-heading"><div><span className="jev-figure-number">Figure 01</span><h3 id="accuracy-title">Selection accuracy by evaluation subset</h3><p>The same 250 cases are evaluated across seven decision systems.</p></div><label className="jev-sort">Order<select value={sort} onChange={e => setSort(e.target.value)}><option value="accuracy">Accuracy</option><option value="name">Name</option></select></label></div>
    <div className="jev-tabs" role="group" aria-label="Accuracy subset">{subsets.map(item => <button key={item.id} type="button" aria-pressed={subset === item.id} onClick={() => setSubset(item.id)}>{item.label}<span>{item.count}</span></button>)}</div>
    <div className="jev-bar-chart" role="img" aria-label={`Selection accuracy on ${selected.count} ${selected.label.toLowerCase()} cases. ${models.map(m => `${shortName(m)} ${pct(m.accuracy[subset])}`).join('; ')}.`}>
      <div className="jev-bar-axis"><span>0</span><span>25</span><span>50</span><span>75</span><span>100%</span></div>
      {models.map(model => <div className="jev-bar-row" key={model.id}><div className="jev-bar-name"><i style={{ background: color(model) }} />{shortName(model)}</div><div className="jev-bar-track"><div className="jev-bar-fill" style={{ width: pct(model.accuracy[subset]), background: color(model) }} /></div><div className="jev-bar-value"><strong>{pct(model.accuracy[subset])}</strong><span>{model.correct[subset]} / {selected.count}</span></div></div>)}
    </div>
    <p className="jev-caption"><strong>{selected.label}, n = {selected.count}.</strong> {selected.note} These are routing decisions, not generated function calls or completed tasks.</p>
  </div>;
}

function SpeedChart({ report }: { report: Report }) {
  const [subset, setSubset] = useState<'overall' | 'positive'>('overall');
  const [stat, setStat] = useState<'p50' | 'mean'>('p50');
  const [selectedId, setSelectedId] = useState(report.models.find(m => /laya/i.test(m.name))?.id || report.models[0].id);
  const latency = (model: Model) => model.latencyBySubset?.[subset === 'overall' ? 'all' : 'positive'] || model.latencyMs;
  const xMax = Math.ceil(Math.max(...report.models.map(m => latency(m)[stat])) / 20) * 20 + 20;
  const x = (value: number) => 68 + value / xMax * 700;
  const y = (value: number) => 328 - value * 244;
  const selected = report.models.find(m => m.id === selectedId) || report.models[0];
  const offsets: Record<string, [number, number]> = { Laya: [12, -6], Von: [12, 20], NanoJev: [12, -10], Kev: [10, 18], Rizzo: [12, 30], Nimble: [6, -31], 'Qwen · SemIf': [-8, -10] };
  return <div className="jev-figure jev-speed-figure" aria-labelledby="speed-title">
    <div className="jev-figure-heading"><div><span className="jev-figure-number">Figure 02 · exploratory timing</span><h3 id="speed-title">Observed decision latency and selection accuracy</h3><p>NVIDIA H100 · heterogeneous runtimes · one recorded decision per case</p></div></div>
    <div className="jev-chart-controls"><label>Cases<select value={subset} onChange={e => setSubset(e.target.value as 'overall' | 'positive')}><option value="overall">All 250 cases</option><option value="positive">200 tool-required cases</option></select></label><label>Latency<select value={stat} onChange={e => setStat(e.target.value as 'p50' | 'mean')}><option value="p50">Median</option><option value="mean">Mean · includes first-call overhead</option></select></label></div>
    <div className="jev-scatter-wrap"><svg viewBox="0 0 830 390" className="jev-scatter" role="img" aria-labelledby="scatter-title scatter-desc"><title id="scatter-title">{`Routing accuracy against recorded ${stat === 'p50' ? 'median' : 'mean'} wall latency`}</title><desc id="scatter-desc">Higher and farther left is better on this selected subset. All measurements are exploratory H100 results. Choose a model below for exact values.</desc>
      {[0, .25, .5, .75, 1].map(tick => <g key={tick}><line x1="68" x2="786" y1={y(tick)} y2={y(tick)} stroke="#e6e9e4" /><text x="52" y={y(tick) + 4} textAnchor="end">{tick * 100}%</text></g>)}
      {[0, 1, 2, 3, 4].map(i => <g key={i}><line x1={x(xMax * i / 4)} x2={x(xMax * i / 4)} y1="72" y2="328" stroke="#f0f0eb" /><text x={x(xMax * i / 4)} y="351" textAnchor="middle">{(xMax * i / 4).toFixed(0)}</text></g>)}
      <text x="68" y="34" className="jev-axis-title">SELECTION ACCURACY ↑</text><text x="418" y="381" textAnchor="middle" className="jev-axis-title">RECORDED WALL LATENCY (MS) →</text>
      {report.models.map(model => { const offset = offsets[shortName(model)] || [10, -10]; return <g key={model.id} className={selectedId === model.id ? 'jev-point is-selected' : 'jev-point'}><title>{`${model.name}: ${pct(model.accuracy[subset])}, ${ms(latency(model)[stat])}`}</title><circle cx={x(latency(model)[stat])} cy={y(model.accuracy[subset])} r={selectedId === model.id ? 10 : 7} fill={color(model)} stroke="#fff" strokeWidth="3" /><text x={x(latency(model)[stat]) + offset[0]} y={y(model.accuracy[subset]) + offset[1]} textAnchor={shortName(model) === 'Qwen · SemIf' ? 'end' : 'start'}>{shortName(model)}</text></g>; })}
    </svg></div>
    <div className="jev-model-picker" role="group" aria-label="Inspect model timing">{report.models.map(model => <button type="button" key={model.id} aria-pressed={selectedId === model.id} onClick={() => setSelectedId(model.id)}><i style={{ background: color(model) }} />{shortName(model)}</button>)}</div>
    <div className="jev-model-detail" aria-live="polite"><strong>{selected.name}</strong><span><b>{pct(selected.accuracy[subset])}</b> selection accuracy</span><span><b>{ms(latency(selected)[stat])}</b> {stat === 'p50' ? 'median' : 'mean'} wall time</span><span>{selected.runtime?.precision || 'See run metadata'}</span></div>
    <p className="jev-caption">No evaluator warm-up or repeated-run timing protocol. HTTP and in-process adapters, precisions and serving paths differ. First recorded calls remain in the aggregates. These values do not establish Mac latency or an architecture-only speed advantage.</p>
  </div>;
}

function CaseExplorer({ report }: { report: Report }) {
  const [query, setQuery] = useState('');
  const [failuresOnly, setFailuresOnly] = useState(false);
  const [modelId, setModelId] = useState(report.models.find(m => /laya/i.test(m.name))?.id || report.models[0].id);
  const [caseId, setCaseId] = useState(report.cases.find(c => c.predictions[modelId]?.correct === false)?.id || report.cases[0].id);
  const filtered = useMemo(() => report.cases.filter(c => `${c.id} ${c.prompt} ${c.goldAction}`.toLowerCase().includes(query.toLowerCase()) && (!failuresOnly || c.predictions[modelId]?.correct === false)), [report, query, failuresOnly, modelId]);
  const active = filtered.find(c => c.id === caseId) || filtered[0];
  const prediction = active?.predictions[modelId];
  const model = report.models.find(m => m.id === modelId)!;
  return <div className="jev-explorer">
    <div className="jev-explorer-top"><span className="jev-figure-number">Per-case predictions</span><span className="jev-live-dot">250 public cases · 1,750 predictions</span></div>
    <div className="jev-explorer-controls"><label>Find a case<input type="search" placeholder="Request, function, or case ID…" value={query} onChange={e => setQuery(e.target.value)} /></label><label>Model<select value={modelId} onChange={e => setModelId(e.target.value)}>{report.models.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div>
    <div className="jev-case-filter"><label><input type="checkbox" checked={failuresOnly} onChange={e => setFailuresOnly(e.target.checked)} /> Only this model’s mistakes</label><span aria-live="polite">{filtered.length} matching {filtered.length === 1 ? 'case' : 'cases'}</span></div>
    {active && prediction ? <>
      <label className="jev-case-select">Case<select value={active.id} onChange={e => setCaseId(e.target.value)}>{filtered.map(c => <option key={c.id} value={c.id}>{c.id} · {c.prompt.slice(0, 80)}</option>)}</select></label>
      <div className="jev-case-body"><div className="jev-case-request"><div className="jev-case-eyebrow">USER REQUEST <span>{active.expectedTools.length ? `${active.options.filter(o => o.kind === 'tool').length || active.options.length - 3} function options` : 'No call expected'}</span></div><p>{active.prompt}</p><div className="jev-case-target"><span>Reference</span><strong>{active.expectedTools.length ? active.expectedTools.join(', ') : 'Any non-tool action'}</strong></div><details><summary>Read all options shown to the model</summary><dl>{active.options.map(option => <div key={option.id}><dt>{option.id}</dt><dd>{option.description}</dd></div>)}</dl></details></div>
      <div className="jev-case-prediction"><div className="jev-case-eyebrow">{shortName(model).toUpperCase()}’S DECISION <span className={prediction.correct ? 'jev-status-good' : 'jev-status-bad'}>{prediction.correct ? 'Correct' : 'Incorrect'}</span></div><h4>{prediction.selectedAction}</h4><p className="jev-case-latency">Recorded wall time · {ms(prediction.latencyMs)}</p><div className="jev-probabilities">{Object.entries(prediction.probabilities || {}).sort((a, b) => b[1] - a[1]).map(([option, probability]) => <div key={option} className="jev-prob-row"><div><span>{option}</span><b>{(probability * 100).toFixed(1)}%</b></div><div className="jev-prob-track"><span style={{ width: pct(probability), background: option === prediction.selectedAction ? color(model) : '#c8d0ca' }} /></div></div>)}</div><p className="jev-microcopy">Saved option probabilities. They are not a calibrated guarantee of correctness.</p></div></div>
      <div className="jev-case-comparison"><span>On this same case</span>{report.models.map(m => <button type="button" key={m.id} onClick={() => { setCaseId(active.id); if (failuresOnly && active.predictions[m.id]?.correct) setFailuresOnly(false); setModelId(m.id); }} aria-pressed={m.id === modelId}><span aria-label={active.predictions[m.id]?.correct ? 'Correct' : 'Incorrect'}>{active.predictions[m.id]?.correct ? '✓' : '×'}</span>{shortName(m)}</button>)}</div>
    </> : <p className="jev-empty">No cases match. Try another search or turn off the mistakes filter.</p>}
  </div>;
}

function ResultsTable({ report }: { report: Report }) {
  return <div className="jev-table-scroll" tabIndex={0} role="region" aria-label="Complete model results, scroll horizontally on small screens"><table className="jev-results-table"><caption>Complete results · all 250 cases</caption><thead><tr><th scope="col">System</th><th scope="col">Selection</th><th scope="col">Tool required</th><th scope="col">No call</th><th scope="col">Median</th><th scope="col">Precision</th></tr></thead><tbody>{report.models.map(m => <tr key={m.id}><th scope="row"><i style={{ background: color(m) }} />{m.name}</th><td><strong>{pct(m.accuracy.overall)}</strong><small>{m.correct.overall}/250</small></td><td>{m.correct.positive}/200</td><td>{m.correct.negative}/50</td><td>{ms(m.latencyMs.p50)}</td><td>{m.runtime?.precision || 'See metadata'}</td></tr>)}</tbody></table></div>;
}

export default function JevRoutingStudy({ initialReport }: { initialReport?: Report } = {}) {
  const [report, setReport] = useState<Report | null>(initialReport || null);
  const [error, setError] = useState(false);
  const [activeSection, setActiveSection] = useState('abstract');
  useEffect(() => {
    if (initialReport) return;
    const controller = new AbortController();
    fetch(DATA_URL, { signal: controller.signal }).then(response => { if (!response.ok) throw new Error('Report unavailable'); return response.json(); }).then(setReport).catch(e => { if (e.name !== 'AbortError') setError(true); });
    return () => controller.abort();
  }, [initialReport]);
  useEffect(() => {
    const originalTitle = document.title;
    document.title = 'Tool Selection with Jev-Style Decision Models: A BFCL V1 Pilot Study | Pritish Yuvraj';
    const observer = new IntersectionObserver(entries => { const entry = entries.find(item => item.isIntersecting); if (entry) setActiveSection(entry.target.id); }, { rootMargin: '-12% 0px -68% 0px' });
    sections.forEach(([id]) => { const element = document.getElementById(id); if (element) observer.observe(element); });
    return () => { observer.disconnect(); document.title = originalTitle; };
  }, []);
  return <div className="jev-study">
    <a className="jev-skip-link" href="#study-content">Skip to article</a>
    <header className="jev-header"><a href="/" className="jev-wordmark">Pritish Yuvraj<span>Research notes</span></a><nav aria-label="Article navigation"><a href="#results">Results</a><a href="#explore">Explore cases</a><a href={HF_URL} target="_blank" rel="noreferrer">Data & code <span aria-hidden="true">↗</span></a></nav></header>
    <main id="study-content">
      <div className="jev-hero"><div className="jev-kicker"><span>Jev-style evaluations</span><i />Research report 01 · September 28, 2026</div><h1>Tool Selection with <br /><em>Jev-Style Decision Models</em></h1><p className="jev-deck">A BFCL V1 pilot study toward efficient on-device personal assistants</p><div className="jev-byline"><span className="jev-avatar">PY</span><div><strong>Pritish Yuvraj</strong><span>Empirical study · initial evaluation</span></div><a href="#abstract">Read the abstract <span aria-hidden="true">↓</span></a></div>
      <div className="jev-hero-metrics"><div><strong>7</strong><span>decision systems</span></div><div><strong>250</strong><span>shared evaluation cases</span></div><div><strong>1</strong><span>routing step per case</span></div><p><span className="jev-small-label">Experimental scope</span>First-step function selection.<br />Short inputs · NVIDIA H100.</p></div></div>
      <div className="jev-article-layout"><aside className="jev-toc"><span className="jev-small-label">Contents</span><nav aria-label="Table of contents">{sections.map(([id, label], index) => <a href={`#${id}`} key={id} aria-current={activeSection === id ? 'location' : undefined}><span>{index === 0 ? '—' : String(index).padStart(2, '0')}</span>{label}</a>)}</nav><a className="jev-toc-download" href={DATA_URL} download>Download the report <span aria-hidden="true">↓</span></a></aside><article className="jev-article">
      <section id="abstract" className="jev-section jev-abstract"><h2>Abstract</h2><div className="jev-prose"><p>On-device personal assistants must select tools from catalogs that compete with conversation history and observations for limited inference resources. A possible design assigns tool selection to a compact decision model and reserves a language model for argument generation and response synthesis. The longer-term objective is reliable selection over extended context in a single prefill decision stage. This report evaluates an initial component of that design: first-step selection on 250 cases derived from Berkeley Function Calling Leaderboard V1. Seven decision systems are compared on 200 tool-required and 50 no-call cases. Bespoke Nimble 9B and frozen Qwen3.5-4B with SemIf each achieve 248/250 (99.2%) under the combined selection metric; Laya achieves 240/250 (96.0%). Recorded H100 timings are reported as exploratory measurements because serving paths and numerical precision differ. These results establish a short-context baseline. Long-context selection, on-device latency, argument correctness, and complete assistant tasks remain unevaluated.</p></div><p className="jev-keywords"><strong>Keywords:</strong> tool selection; decision models; function calling; on-device assistants; BFCL</p></section>

      <section id="why" className="jev-section"><div className="jev-section-label">01 / Introduction</div><h2>Efficient tool selection for on-device assistants</h2><div className="jev-prose"><p>A personal assistant operating on a local computer may need to condition its next action on the user request, conversation history, previous tool results, and an available tool catalog. As this decision context grows, encoding cost and memory requirements become relevant constraints. A research objective is therefore to identify compact models that retain tool-selection accuracy under long contexts and can produce a decision without autoregressively generating a complete tool call.</p><p>The proposed architecture assigns action selection to a decision model, argument generation and response synthesis to a chat model, and execution and permission enforcement to a harness. Selection is repeated after each tool observation, with fallback to the chat model when the decision policy abstains. The present experiment evaluates only the initial selection step.</p></div>
      <div className="jev-flow" aria-label="Proposed on-device assistant architecture; only initial selection is evaluated"><div className="jev-flow-step"><span>01 · Input</span><h3>Decision context</h3><p>Request, history,<br />observations, tool catalog</p></div><span className="jev-flow-arrow" aria-hidden="true">→</span><div className="jev-flow-step jev-flow-decision"><span>02 · Selection</span><h3>Decision model</h3><p>Score available actions;<br />select a tool or abstain</p><b>Evaluated component</b></div><span className="jev-flow-arrow" aria-hidden="true">→</span><div className="jev-flow-step"><span>03 · Completion</span><h3>Chat model + harness</h3><p>Arguments, execution,<br />response synthesis</p></div></div>
      <div className="jev-prose"><h3>1.1 Decision interface and prefill</h3><p>Here, <em>Jev-style</em> describes a decision interface over a finite set of supplied actions. For input context <em>x</em> and action set <em>A</em>, the system selects the highest-scoring action. The evaluated systems return action scores or probabilities rather than a generated answer sequence. This terminology describes the interface; the underlying architectures and scoring implementations differ.</p><div className="jev-method-equation" aria-label="The selected action is the action with the highest model score given the input context and available actions">â = arg max<sub>a ∈ A</sub> s<sub>θ</sub>(a | x, A)</div><p><strong>Single-prefill tool selection is the deployment target:</strong> encode the decision context and obtain a bounded action readout without decoding a multi-token tool call. The current comparison does not establish that every backend performs one shared physical forward pass across all candidates. For example, candidate-conditioned encoders and direct answer-logit readouts use different computation paths <a href="#ref-semif">[7]</a><a href="#ref-nanojev">[10]</a>.</p><p>Removing autoregressive answer generation addresses one source of inference cost. The model must still process its input context, and the chat model may require some of the same evidence to construct arguments. Any overall latency benefit must therefore be measured across the complete assistant workflow.</p><h3>1.2 Scope and related work</h3><p>This study evaluates existing open decision systems and scoring methods. Related BFCL dispatch evaluations and decision-model comparisons have been released by Blobfish, OD1, and LangWatch <a href="#ref-blobfish">[11]</a><a href="#ref-od1">[12]</a><a href="#ref-langwatch">[13]</a>. The contribution here is a documented BFCL V1 conversion, a frozen evaluation subset, and an inspectable comparison of seven systems on identical cases. No new model architecture is introduced.</p></div></section>

      <section id="setup" className="jev-section"><div className="jev-section-label">02 / Experimental setup</div><h2>Dataset construction and evaluation protocol</h2><div className="jev-prose"><h3>2.1 Source data and selection</h3><p>The evaluation derives from the BFCL V1 data in the Gorilla repository <a href="#ref-bfcl">[1]</a>, pinned to tag <code>v1.0</code> and commit <code>9df5c346ee0556c8a7cb09fd7206a39aadd904c2</code>. From a 2,000-case converted corpus, 250 examples were selected using category quotas, deterministic hash ranking, and normalized-request deduplication. Eligibility required an unambiguous next action and a usable reference label. Parallel-call cases were excluded because they do not define a unique first action.</p><p>The selected set contains 120 <code>multiple_function</code>, 30 <code>executable_multiple_function</code>, 35 <code>simple</code>, 15 <code>executable_simple</code>, and 50 <code>relevance</code> examples. The relevance category was filtered through a reviewed 55-case allowlist before selection. The exact seed, review decisions, retained source references, and selection manifest are included in the dataset release <a href="#ref-dataset">[2]</a>.</p></div>
      <div className="jev-composition"><span className="jev-figure-number">Evaluation composition · n = 250</span><div className="jev-composition-track" role="img" aria-label="150 multiple-tool cases, 50 one-tool cases, and 50 no-call cases"><div style={{ width: '60%' }}>150</div><div style={{ width: '20%' }}>50</div><div style={{ width: '20%' }}>50</div></div><div className="jev-composition-labels"><div><i /><strong>Multiple tools</strong><span>150 cases · a function is required</span></div><div><i /><strong>One tool</strong><span>50 cases · the function is required</span></div><div><i /><strong>No call</strong><span>50 cases · no function fits</span></div></div></div>
      <div className="jev-prose"><h3>2.2 Decision inputs and systems</h3><p>Each case supplies a user request, one to four function options, and three non-tool actions: <code>no_tool</code>, <code>clarify</code>, and <code>cannot_answer</code>. Function descriptions are capped at 120 characters. Full argument schemas and reference answers are retained in the release for inspection but are excluded from the decision input. The semantic inputs are shared; prompt serialization and tokenization are backend-specific. Laya’s rendered inputs span 104–271 tokens.</p><p>The evaluated systems are Laya typed-decisions <a href="#ref-laya">[3]</a>, Kev-0.8B <a href="#ref-kev">[4]</a>, Bespoke Nimble 9B <a href="#ref-nimble">[5]</a>, Qwen3.5-4B with SemIf <a href="#ref-qwen">[6]</a><a href="#ref-semif">[7]</a>, Rizzo Flow 4B Q8_0 <a href="#ref-rizzo">[8]</a>, Von 1.3 with decision chains disabled <a href="#ref-von">[9]</a>, and NanoJev unified-games-v1 <a href="#ref-nanojev">[10]</a>. SemIf scores answer-option logits from frozen Qwen weights; it is a readout method, not an additional trained checkpoint. No model is fine-tuned in this experiment. All seven systems returned predictions for all 250 cases, without recorded evaluation errors or retries.</p><h3>2.3 Selection metric</h3><p>For a tool-required case, a prediction is correct only if the selected function matches the reference. For a no-call case, any of the three non-tool actions is accepted. This aggregation follows BFCL’s distinction between function calls and no-call responses; its labels do not separately supervise clarification and inability. The aggregate metric is:</p><div className="jev-method-equation">Selection accuracy = (correct function selections + correct non-tool selections) / 250</div><p>Results are also reported separately for the 200 tool-required cases, the 150 multiple-tool cases, and both 50-case controls. These scores evaluate the selected action. Argument values, execution outcomes, and final responses are outside the protocol.</p></div>
      <p className="jev-note"><strong>Evaluation identity.</strong> This is a derived routing benchmark with a defined selection metric. Its scores are not directly comparable to official BFCL function-calling leaderboard scores.</p></section>

      <section id="results" className="jev-section"><div className="jev-section-label">03 / Selection accuracy</div><h2>Results on the frozen evaluation set</h2><div className="jev-prose"><p>On the combined 250-case metric, Bespoke Nimble 9B and Qwen3.5-4B with SemIf each obtain 248 correct selections (99.2%). Laya obtains 240 (96.0%). On the 200 tool-required cases, the corresponding counts are 200, 198, and 197. The no-call subset accounts for the difference between these views.</p><p>Figure 1 reports the aggregate and subset results. As deterministic controls on the same 250 cases, always selecting the first offered function obtains 106/250 (42.4%), while always selecting a non-tool action obtains 50/250 (20.0%). These controls are provided in the selection manifest <a href="#ref-dataset">[2]</a>.</p></div>
      {report ? <><AccuracyChart report={report} /><ResultsTable report={report} /></> : <div className="jev-loading" role="status">{error ? <>The interactive report could not load. <a href={HF_URL}>Read the published data on Hugging Face.</a></> : 'Loading the recorded results…'}</div>}
      <div className="jev-findings"><div><span>01</span><h3>Function selection</h3><p>Laya selects the reference function in 197/200 tool-required cases, including 147/150 multiple-tool cases. This observation concerns the supplied short descriptions.</p></div><div><span>02</span><h3>Frozen-model readout</h3><p>Qwen3.5-4B with SemIf obtains 198/200 tool-required selections and 50/50 no-call selections. Direct-logit scoring provides a relevant baseline for specialized checkpoints.</p></div><div><span>03</span><h3>Domain specialization</h3><p>NanoJev obtains 38/200 tool-required selections and 50/50 no-call selections. Its evaluated checkpoint targets games; the frequent abstention is an out-of-domain observation.</p></div></div>
      <div className="jev-prose"><p>The leading tool-required scores differ by only a few cases. These point estimates do not establish statistical equivalence or a general model ranking. The subset analysis is particularly relevant because the 50 positive one-tool controls do not require distinguishing among multiple candidate functions.</p></div></section>

      <section id="speed" className="jev-section"><div className="jev-section-label">04 / Latency analysis</div><h2>Exploratory measurements on H100</h2><div className="jev-prose"><p>The experiments were recorded on NVIDIA H100 hardware. Each plotted value is computed from the saved per-case wall-time measurements, with one recorded decision per case and no uniform warm-up or repeated-trial protocol. The measurements include first recorded calls. They use different precision settings and serving paths, including HTTP services and in-process scorers.</p><p>Figure 2 pairs selection accuracy with latency over the same selected subset. Median latency reduces the influence of isolated first-call overhead; the mean remains available to expose that sensitivity. These observations characterize the tested configurations. They do not isolate architecture effects or quantify an on-device speedup.</p></div>
      {report && <SpeedChart report={report} />}
      <div className="jev-prose"><p>For a future assistant evaluation, the relevant measurement is time to a correctly completed task, including selection, argument generation, tool execution, fallback, retries, and response synthesis. A reduction in selection latency is useful only if it survives this complete workflow.</p></div>
      <div className="jev-equation"><span className="jev-small-label">Future system-level measurement</span><p>Context <span>→</span> selection <span>→</span> arguments <span>→</span> execution <span>→</span> response</p><strong>Report task success together with end-to-end wall time.</strong></div></section>

      <section id="explore" className="jev-section"><div className="jev-section-label">05 / Prediction analysis</div><h2>Per-case inspection</h2><div className="jev-prose"><p>The released report contains all 250 requests and 1,750 predictions, including offered actions, selected actions, recorded score distributions, and wall times. The interface below supports comparison on identical cases and filtering by a selected system’s errors. Calibration on this evaluation distribution has not been established; the recorded probabilities should not be interpreted as empirical correctness guarantees.</p></div>{report && <CaseExplorer report={report} />}<p className="jev-caption">The displayed records contain public benchmark cases and model predictions. No private assistant conversations are included.</p></section>

      <section id="limits" className="jev-section"><div className="jev-section-label">06 / Limitations</div><h2>Scope of the evidence</h2><div className="jev-limit-list"><div><span>01</span><div><h3>Context length and catalog size</h3><p>The cases contain one to four concise function descriptions, with Laya inputs of 104–271 tokens. The experiment does not measure retention of relevant evidence across long histories, performance with large catalogs, or memory scaling. Long-context single-prefill selection remains a deployment objective.</p></div></div><div><span>02</span><div><h3>Single-step evaluation</h3><p>Only the initial decision is scored. The evaluation does not include tool observations, stopping after task completion, recovery from tool errors, permission escalation, or argument generation.</p></div></div><div><span>03</span><div><h3>Sampling and label semantics</h3><p>The 250 cases form a selected subset with fixed quotas and reviewed exclusions. No-call labels merge three non-tool actions, and some positive requests could be answered directly outside the BFCL labeling convention. The scores therefore depend on this protocol.</p></div></div><div><span>04</span><div><h3>Training overlap and domain mismatch</h3><p>BFCL is public, and exposure during model training has not been excluded. The systems also differ in training data and intended domains. NanoJev’s game-oriented checkpoint is evaluated outside its documented training workload.</p></div></div><div><span>05</span><div><h3>Timing and confidence</h3><p>Precision, kernels, request boundaries, and candidate-scoring implementations differ. No repeated-run latency confidence intervals or probability calibration are reported. The results do not determine an assistant fallback threshold.</p></div></div></div></section>

      <section id="next" className="jev-section"><div className="jev-section-label">07 / Conclusion</div><h2>Toward long-context on-device tool selection</h2><div className="jev-prose"><p>This experiment establishes a reproducible conversion and an inspectable short-context selection baseline for seven existing decision systems. Several configurations achieve high selection accuracy under the defined BFCL-derived protocol. The results support further evaluation of a separate tool-selection stage in a local assistant; they do not establish the effectiveness of the complete architecture.</p><p>The next study should test whether selection accuracy is retained as the decision context and catalog increase, and whether avoiding autoregressive tool-call decoding produces a measurable benefit on constrained devices. The following extensions follow directly from the present limitations.</p></div><div className="jev-next-grid"><div><span>01 / Context scaling</span><h3>Long histories and larger catalogs</h3><p>Vary input length and tool count independently, including distractors and evidence at different positions. Report accuracy, latency, memory, and truncation behavior.</p></div><div><span>02 / Decision trajectories</span><h3>Selection after observations</h3><p>Evaluate continuation, abstention, recovery, and stopping on held-out assistant scenarios. Calibrate any fallback policy on separate development data.</p></div><div><span>03 / On-device evaluation</span><h3>Controlled complete-task comparison</h3><p>Keep the chat model, tools, and permission policy fixed. Compare chat-only routing with a decision-model stage on the same hardware and tasks.</p></div></div><div className="jev-artifact-cta"><div><span className="jev-small-label">Research artifacts</span><h3>Dataset, predictions, and conversion code</h3><p>The release preserves source references and exact checkpoint identifiers, allowing the reported aggregates to be independently inspected.</p></div><a href={HF_URL} target="_blank" rel="noreferrer">Dataset and artifacts <span aria-hidden="true">↗</span></a></div></section>

      <section id="references" className="jev-section jev-references"><div className="jev-section-label">08 / References</div><h2>Datasets, models, and related work</h2><p>References [1–2] identify the data used in this experiment; [3–10] identify every evaluated checkpoint and the SemIf scoring method. Model links below point to the evaluated revisions. The full report records additional runtime and weight provenance.</p><ol className="jev-bibliography">
        <li id="ref-bfcl"><a href="https://proceedings.mlr.press/v267/patil25a.html" target="_blank" rel="noreferrer">Patil, S. G., Mao, H., Yan, F., Ji, C. C.-J., Suresh, V., Stoica, I., and Gonzalez, J. E. (2025). The Berkeley Function Calling Leaderboard (BFCL): From Tool Use to Agentic Evaluation of Large Language Models.</a><span>ICML, Proceedings of Machine Learning Research 267:48371–48392. Data used here: <a href="https://github.com/ShishirPatil/gorilla/tree/9df5c346ee0556c8a7cb09fd7206a39aadd904c2/berkeley-function-call-leaderboard/data" target="_blank" rel="noreferrer">BFCL V1, tag v1.0, commit 9df5c346ee0556c8a7cb09fd7206a39aadd904c2</a>. <a href="https://gorilla.cs.berkeley.edu/blogs/8_berkeley_function_calling_leaderboard.html" target="_blank" rel="noreferrer">Original V1 release description.</a></span></li>
        <li id="ref-dataset"><a href="https://huggingface.co/datasets/pyuvraj/bfcl-v1-jev-routing/tree/3edb43c0132ac94e65ea71c566dbe521df6c78f1" target="_blank" rel="noreferrer">Yuvraj, P. (2026). BFCL V1 Jev Routing Pilot.</a><span>250-case derived test set, source provenance, conversion code, and recorded predictions. Release 3edb43c0132ac94e65ea71c566dbe521df6c78f1.</span></li>
        <li id="ref-laya"><a href="https://huggingface.co/convaiinnovations/laya-typed-decisions/tree/1a793eb568e6718f15941d08f85432581df534e3" target="_blank" rel="noreferrer">Convai Innovations. Laya typed-decisions.</a><span>Model checkpoint 1a793eb568e6718f15941d08f85432581df534e3. The run used the matching typed-decisions weights from the pinned Laya bundle; weight identity is recorded in the report.</span></li>
        <li id="ref-kev"><a href="https://huggingface.co/jaredpalmer/kev-0.8b/tree/9a45d25eb2ab761841196625383fa1dff0e56c1e" target="_blank" rel="noreferrer">Palmer, J. Kev-0.8B.</a><span>Model checkpoint 9a45d25eb2ab761841196625383fa1dff0e56c1e. <a href="https://huggingface.co/Qwen/Qwen3.5-0.8B-Base/tree/dc7cdfe2ee4154fa7e30f5b51ca41bfa40174e68" target="_blank" rel="noreferrer">Qwen3.5-0.8B-Base backbone</a>; evaluated through the native decision server.</span></li>
        <li id="ref-nimble"><a href="https://huggingface.co/bespokelabs/Bespoke-Nimble-9B/tree/bd792f44ec8e265be861bfcdf4e05967ffe0e858" target="_blank" rel="noreferrer">Bespoke Labs. Bespoke-Nimble-9B.</a><span>Adapter revision bd792f44ec8e265be861bfcdf4e05967ffe0e858 with <a href="https://huggingface.co/Qwen/Qwen3.5-9B/tree/c202236235762e1c871ad0ccb60c8ee5ba337b9a" target="_blank" rel="noreferrer">pinned Qwen3.5-9B base weights</a>; native candidate scorer, BF16.</span></li>
        <li id="ref-qwen"><a href="https://huggingface.co/Qwen/Qwen3.5-4B/tree/851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a" target="_blank" rel="noreferrer">Qwen Team. (2026). Qwen3.5: Towards Native Multimodal Agents. Qwen3.5-4B checkpoint.</a><span>Frozen checkpoint 851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a, evaluated in BF16 using the SemIf readout [7].</span></li>
        <li id="ref-semif"><a href="https://github.com/TheoLeeCJ/SemIf-OpenJev" target="_blank" rel="noreferrer">TheoLeeCJ. SemIf / SemIf-OpenJev.</a><span>Direct option-logit scoring method. This reference identifies the scoring implementation; the evaluated model weights are Qwen3.5-4B [6].</span></li>
        <li id="ref-rizzo"><a href="https://huggingface.co/rizzoaiacademy/rizzo-flow/tree/55633c8cbd2b826bd3eefdeb05310450996649df" target="_blank" rel="noreferrer">Rizzo AI Academy. Rizzo Flow.</a><span>Revision 55633c8cbd2b826bd3eefdeb05310450996649df; Q8_0 GGUF weights, based on <a href="https://huggingface.co/XHToken/Spark-X2.5-4B/tree/0bcb35678590218655dff3765b9e61c83b35e9c4" target="_blank" rel="noreferrer">Spark-X2.5-4B</a>.</span></li>
        <li id="ref-von"><a href="https://huggingface.co/wfzyx/von/tree/43bbca0fb17f424539416ee8eb3de33cfc3dacf3" target="_blank" rel="noreferrer">Panisa, V. H. Von.</a><span>Revision 43bbca0fb17f424539416ee8eb3de33cfc3dacf3; Von 1.3 with decision chains disabled. Numerical precision was not recorded in the saved run metadata.</span></li>
        <li id="ref-nanojev"><a href="https://huggingface.co/C-Tianyu/NanoJev/tree/047b927b30882a1138fc504821b82ac145a4b81a" target="_blank" rel="noreferrer">C-Tianyu / TianyuCodings. NanoJev.</a><span>Revision 047b927b30882a1138fc504821b82ac145a4b81a; unified-games-v1 checkpoint with a <a href="https://huggingface.co/Qwen/Qwen3-0.6B/tree/c1899de289a04d12100db370d81485cdf75e47ca" target="_blank" rel="noreferrer">Qwen3-0.6B backbone</a>, evaluated in BF16.</span></li>
        <li id="ref-blobfish"><a href="https://blobfish.ai/benchmarks/typed-decision-bench/tasks/bfcl-tool-dispatch" target="_blank" rel="noreferrer">Blobfish AI. Typed Decision Bench: BFCL Tool Dispatch.</a><span>Related conversion of BFCL tool dispatch to a typed-decision task. This dataset is not used in the present experiment.</span></li>
        <li id="ref-od1"><a href="https://huggingface.co/mvbalaji/od1-base" target="_blank" rel="noreferrer">mvbalaji. OD1-Base.</a><span>Related open decision-model work and BFCL-derived evaluation. OD1 is not evaluated in this study.</span></li>
        <li id="ref-langwatch"><a href="https://langwatch.ai/compare/jev-vs-all" target="_blank" rel="noreferrer">LangWatch. Jev vs open models up to 28B, benchmarked.</a><span>Related decision-system comparison; its measurements are not combined with the results reported here.</span></li>
      </ol><p className="jev-reference-note">Source model cards and project documentation accessed September 28, 2026. “Jev-style” denotes the decision interface in this report; <a href="https://typesafe.ai/" target="_blank" rel="noreferrer">TypeSafe’s Jev model</a> is not evaluated.</p></section>
      </article></div>
    </main><footer className="jev-footer"><a href="/">← Back to Pritish Yuvraj</a><span>Jev-style evaluations / Research report 01</span><a href="#study-content">Back to top ↑</a></footer>
  </div>;
}
